# Grid Search CV

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
df = sns.load_dataset('iris')

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop('species', axis = 1)
y = df['species']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
model_knn = KNeighborsClassifier(n_neighbors =5)

In [12]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
model_knn.score(X_test,y_test)

0.98

In [14]:
from sklearn.svm import SVC

In [15]:
model_svm = SVC(C = 10,kernel='linear',gamma='auto')

In [16]:
model_svm.fit(X_train,y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [17]:
model_svm.score(X_test,y_test)

1.0

# Grid Search CV

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
    },cv = 5,return_train_score =False)

In [20]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [21]:
classifier.cv_results_

{'mean_fit_time': array([0.00365033, 0.00283885, 0.00305309, 0.0034389 , 0.00498562,
        0.00363541, 0.00279737, 0.00219994]),
 'std_fit_time': array([0.00101811, 0.0003815 , 0.00091774, 0.00188672, 0.00283183,
        0.0018166 , 0.00116172, 0.00019897]),
 'mean_score_time': array([0.00404954, 0.00322452, 0.003264  , 0.00278316, 0.00215487,
        0.00208654, 0.00249934, 0.00215688]),
 'std_score_time': array([0.00087861, 0.00169105, 0.00137704, 0.00132151, 0.00023674,
        0.00050535, 0.00165967, 0.00116961]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [22]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003650,0.001018,0.004050,0.000879,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002839,0.000382,0.003225,0.001691,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003053,0.000918,0.003264,0.001377,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003439,0.001887,0.002783,0.001322,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004986,0.002832,0.002155,0.000237,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003635,0.001817,0.002087,0.000505,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002797,0.001162,0.002499,0.001660,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002200,0.000199,0.002157,0.001170,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [23]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

# Rendomized Search CV

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
    },n_iter = 4,cv = 5,return_train_score =False)

In [26]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [27]:
results =pd.DataFrame(classifier_r.cv_results_)

In [28]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003739,0.001572,0.004199,0.002656,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
1,0.002914,0.000839,0.003004,0.001448,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002690,0.000526,0.002248,0.000981,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003607,0.001509,0.002290,0.000776,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [29]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1       linear         0.980000
2       10          rbf         0.980000
3        1          rbf         0.980000